// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var clock, event, timeout;

  clock = {};

  event = require('newtonjs-event');

  timeout = null;

  clock.tick = function(interval) {
    var fn;
    return (fn = function() {
      event.emit('tick');
      return timeout = setTimeout(fn, interval);
    })();
  };

  clock.tock = function(fn) {
    return event.on('tick', fn);
  };

  clock.stop = function() {
    return clearTimeout(timeout);
  };

  module.exports = clock;

}).call(this);
